language: python
python:
  - "2.7"
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - /tmp/proto3.1.0

install:
  - pip install pip --upgrade
# RDFLib requres html5lib;  html5lib requires setuptools version 18.5 or above;
  - pip install setuptools==25.1.0
  - python setup.py sdist
  - pip install dist/ga4gh*.tar.gz -c constraints.txt
# every installable in setup.py's entry_points should be tested here
  - ga4gh_configtest --version
  - ga4gh_server --version
  - ga2vcf --version
  - ga2sam --version
  - ga4gh_repo --version

before_script:
  - pip install -r dev-requirements.txt
  - python scripts/build_test_data.py 
    
before_install:
    - bash tools/travis-install-protoc.sh 3.1.0
    - export PATH=/tmp/proto3.1.0/bin:$PATH

# run_tests.py runs everything under the script: tag so only put commands
# under it that we want to run (and want to be able to run) as local tests
script: 
  - flake8 configtest_dev.py convert_error_code.py
           ga2sam_dev.py ga2vcf_dev.py repo_dev.py server_dev.py
           setup.py
           tests ga4gh scripts
  - python -mnose tests 
              --with-coverage --cover-package ga4gh.server
              --cover-inclusive --cover-min-percentage 85
              --cover-branches --cover-erase
  - make clean -C docs
  - make -C docs

after_success:
# run codecov
  - bash <(curl -s https://codecov.io/bash)
