language: python
python:
  - "2.7"
sudo: false

before_install:
  - wget 'http://www.well.ox.ac.uk/~jk/wheelhouse.tar'
  - tar -xvf wheelhouse.tar

install:
  - pip install --use-wheel --find-links=wheelhouse/ -r requirements.txt
  - python setup.py install

before_script:
  # the following two lines are to prevent travis from
  # verbosely complaining about a security problem; see issue 54
  - mkdir $HOME/.python-eggs
  - chmod og-w $HOME/.python-eggs

# run_tests.py runs everything under the script: tag so only put commands
# under it that we want to run (and want to be able to run) as local tests
script: 
  - flake8 *.py tests ga4gh scripts --exclude=ez_setup.py
  - nosetests --with-coverage --cover-package ga4gh
              --cover-inclusive --cover-min-percentage 85
              --cover-branches --cover-erase
  - make clean -C docs
  - make -C docs
