name: server-conda-env
channels:
- ioos
dependencies:
- protobuf=3.0.0=py27_0
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- python=2.7.11=0
- readline=6.2=2
- setuptools=23.0.0=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
    - ga4gh-common==0.0.7
    - ga4gh-schemas==0.6.0a10.post1
    - ga4gh-client==0.6.0a10
    - sphinx-argparse==0.1.15
    - sphinx==1.5.1
    - pysam==0.9.0
    - RDFLib==4.2.1
    - peewee==2.8.5
